version: '3'

services:

  webapp:
    build: 
      context: ./webapp
    restart: always
    ports:
      - 80:80
    environment:
      DB_HOST: db
      DB_USER: hello
      DB_PASS: c458c7t9x34fZ
      DB_NAME: hello

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: hello 
      MARIADB_USER: hello
      MARIADB_PASSWORD: c458c7t9x34fZ
      MARIADB_ROOT_PASSWORD: 459mx4t83xdoRrwrdd


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8765:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
